spring.application.name=MySpringbootLab

# 기본 설정
myprop.username=springboot
myprop.port=${random.int(1,100)}

# 기본 프로파일 설정 (기본적으로 test를 사용하도록 설정해둘 수 있습니다)
#spring.profiles.active=test

# 기존 테이블을 유지하도록 수정
spring.jpa.hibernate.ddl-auto=update

# 실제로 들어가는 값을 로그로 보고 싶다면 아래 설정 추가
logging.level.org.hibernate.orm.jdbc.bind=trace

# MariaDB 설정
spring.datasource.url=jdbc:mariadb://localhost:3306/lab_db
spring.datasource.username=lab
spring.datasource.password=lab
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

